name: Audit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run AppSec Aviator audit
        uses: fortify/github-action@v3
        env:
          SSC_URL: ${{vars.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SSC_APPVERSION: '${{vars.APPLICATION_NAME}}:${{github.ref_name}}'
          AVIATOR_URL: ${{vars.AVIATOR_URL}}
          AVIATOR_APP: ${{vars.APPLICATION_NAME}}
          AVIATOR_TOKEN: ${{secrets.AVIATOR_TOKEN}}
          AVIATOR_LOGIN_EXTRA_OPTS: "--tenant ${{vars.AVIATOR_TENANT}}"
          DO_WAIT: true
          DO_JOB_SUMMARY: true
