name: FoD Remediate

on:
  workflow_dispatch:

jobs:
  create_pr_with_remediation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v3
        with:
          fcli: ${{vars.FCLI_VERSION}}

      - name: FoD session login
        run: |
          fcli fod session login \
            --url "${{ vars.FOD_URL }}" \
            --tenant "${{ secrets.FOD_TENANT }}" \
            --user "${{ secrets.FOD_USER }}" \
            --password "${{ secrets.FOD_PAT }}"

      - name: Apply remediations
        run: fcli aviator fod apply-remediations --release "${{ vars.FOD_RELEASE }}" --source-dir .

      - name: FoD session logout
        if: always()
        run: fcli fod session logout

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'auto-remediation by OpenText SAST Aviator'
          branch: aviator/remediate-${{ github.run_id }}
          delete-branch: true
          title: 'Remediation of security issues detected by OpenText SAST'
          body: |
            Remediation of security issues detected by OpenText SAST.
            This PR was automatically created by OpenText SAST Aviator.
            Please review carefully before merging.
